language: python
os: linux
dist: bionic
git:
  depth: false
services:
  - xvfb

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    # - python: 3.8  # Not yet supported.

before_script:
  - python -m pip install -U pip
  - python -m pip install -U pytest
  - python -m pip install -r requirements.txt
install:
  - python -m pip install .
script:
  - pytest --pyargs DeepRTS



notifications:
  webhooks: https://discordapp.com/api/webhooks/299549422986067968/0TjN9PW6LcP7Nc-gqFg5nh21mDsww9Qp6vG_F8734A2d_iwPVNRUdx_xUi-xo86pvDHW/travis
